apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-sc
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-auto
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sc-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-local
  template:
    metadata:
      labels:
        app: nginx-local
    spec:
      containers:
        - name: nginx-local-c
          image: nginx:alpine
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          persistentVolumeClaim:
            claimName: pvc-local-auto