apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo  # nombre del PV
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce   # porque tenemos un unico nodo con Minikube
#  storageClassName: slow   --> en caso querramos asociarlo a un StorageClass --> indicar el nombre del storageClass
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
  hostPath:
    path: /mnt/data/pv1  # se monta en el nodo de minikube
  persistentVolumeReclaimPolicy: Retain
