apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-demo  # nombre del PV
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce   # porque tenemos un unico nodo con Minikube
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
  persistentVolumeReclaimPolicy: Retain
